const firstName = "Angela"
const greeting = "Welcome"
const endOfMessage = "to learning JavaScript with friends"
console.log = "%greeting% %firstname% %endOfMessage%"
console.log = "firstName + greeting + endOfMessage"